version: '3.4'

networks:
  bridge-network:
    driver: bridge

services:
  ImMicro.api:
    image: ${DOCKER_REGISTRY-}ImMicroapi
    restart : always
    depends_on:
      - "database_postgres"
      - "database_redis"
      - "message_rabbitmq"
    build:
      context: .
      dockerfile: ImMicro.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: "DockerCompose"
    networks:
      - bridge-network

  ImMicro.scheduleService:
    image: ${DOCKER_REGISTRY-}immicroscheduleservice
    restart: always
    depends_on:
      - "database_postgres"
      - "database_redis"
      - "message_rabbitmq"
    build:
      context: .
      dockerfile: ImMicro.ScheduleService/Dockerfile
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "DockerCompose"
    networks:
      - bridge-network

  ImMicro.consumer:
    image: ${DOCKER_REGISTRY-}immicroconsumer
    restart: always
    depends_on:
      - "database_postgres"
      - "database_redis"
      - "message_rabbitmq"
    build:
      context: .
      dockerfile: ImMicro.Consumer/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "DockerCompose"
    networks:
      - bridge-network

  database_postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456789.tY"
      POSTGRES_DB: "TYDB"
    networks:
      - bridge-network

  database_redis:
    image: "redis:alpine"
    command: redis-server --requirepass 123456789.tY
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - bridge-network

  message_rabbitmq:
    image: "rabbitmq:3.8.3-management"
    #    container_name: rabbitmq_docker
    #    hostname: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "turhany"
      RABBITMQ_DEFAULT_PASS: "turhany"
      RABBITMQ_DEFAULT_VHOST: "immicro"
    networks:
      - bridge-network