//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImMicro.Resources.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImMicro.Resources.App.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Campaign_InfluencerState_Accepted {
            get {
                return ResourceManager.GetString("Campaign_InfluencerState_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied.
        /// </summary>
        public static string Campaign_InfluencerState_Applied {
            get {
                return ResourceManager.GetString("Campaign_InfluencerState_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Campaign_InfluencerState_Rejected {
            get {
                return ResourceManager.GetString("Campaign_InfluencerState_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed.
        /// </summary>
        public static string Campaign_ManagementType_Managed {
            get {
                return ResourceManager.GetString("Campaign_ManagementType_Managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Service.
        /// </summary>
        public static string Campaign_ManagementType_SelfService {
            get {
                return ResourceManager.GetString("Campaign_ManagementType_SelfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Campaign_State_Accepted {
            get {
                return ResourceManager.GetString("Campaign_State_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Campaign_State_Canceled {
            get {
                return ResourceManager.GetString("Campaign_State_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Campaign_State_Completed {
            get {
                return ResourceManager.GetString("Campaign_State_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Campaign_State_Expired {
            get {
                return ResourceManager.GetString("Campaign_State_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Campaign_State_Paused {
            get {
                return ResourceManager.GetString("Campaign_State_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting For Approve.
        /// </summary>
        public static string Campaign_State_WaitingForApprove {
            get {
                return ResourceManager.GetString("Campaign_State_WaitingForApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting For Payment.
        /// </summary>
        public static string Campaign_State_WaitingForPayment {
            get {
                return ResourceManager.GetString("Campaign_State_WaitingForPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting For Brand Response.
        /// </summary>
        public static string Campaign_State_WaitingForRevision {
            get {
                return ResourceManager.GetString("Campaign_State_WaitingForRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Campaign_Type_Action {
            get {
                return ResourceManager.GetString("Campaign_Type_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string Campaign_Type_Click {
            get {
                return ResourceManager.GetString("Campaign_Type_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Campaign_Type_Install {
            get {
                return ResourceManager.GetString("Campaign_Type_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Campaign_Type_Sell {
            get {
                return ResourceManager.GetString("Campaign_Type_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymouse.
        /// </summary>
        public static string CompanyType_Anonymous {
            get {
                return ResourceManager.GetString("CompanyType_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited.
        /// </summary>
        public static string CompanyType_Limited {
            get {
                return ResourceManager.GetString("CompanyType_Limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string CompanyType_Personal {
            get {
                return ResourceManager.GetString("CompanyType_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar.
        /// </summary>
        public static string Currency_Dollar {
            get {
                return ResourceManager.GetString("Currency_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        public static string Currency_Euro {
            get {
                return ResourceManager.GetString("Currency_Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish Lira.
        /// </summary>
        public static string Currency_TL {
            get {
                return ResourceManager.GetString("Currency_TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Forgot_Password_Mail_Subject {
            get {
                return ResourceManager.GetString("Forgot_Password_Mail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your email exists on our system then you will receive an email shortly with instructions on how to reset your password..
        /// </summary>
        public static string Forgot_Password_Message {
            get {
                return ResourceManager.GetString("Forgot_Password_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password token not found..
        /// </summary>
        public static string Forgot_Password_Token_Not_Found {
            get {
                return ResourceManager.GetString("Forgot_Password_Token_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password token was used. Please request new one..
        /// </summary>
        public static string Forgot_Password_Token_Used_Message {
            get {
                return ResourceManager.GetString("Forgot_Password_Token_Used_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not found..
        /// </summary>
        public static string GetToken_Not_Found_Message {
            get {
                return ResourceManager.GetString("GetToken_Not_Found_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string InfluencerState_Accepted {
            get {
                return ResourceManager.GetString("InfluencerState_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string InfluencerState_Waiting {
            get {
                return ResourceManager.GetString("InfluencerState_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string PaymentState_Paid {
            get {
                return ResourceManager.GetString("PaymentState_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string PaymentState_Rejected {
            get {
                return ResourceManager.GetString("PaymentState_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string PaymentState_Waiting {
            get {
                return ResourceManager.GetString("PaymentState_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string PaymentType_Bonus {
            get {
                return ResourceManager.GetString("PaymentType_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Payment.
        /// </summary>
        public static string PaymentType_Brand {
            get {
                return ResourceManager.GetString("PaymentType_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string PaymentType_Refund {
            get {
                return ResourceManager.GetString("PaymentType_Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check your request..
        /// </summary>
        public static string SignUp_Check_Request_Message {
            get {
                return ResourceManager.GetString("SignUp_Check_Request_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string UserType_Admin {
            get {
                return ResourceManager.GetString("UserType_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string UserType_Brand {
            get {
                return ResourceManager.GetString("UserType_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influencer.
        /// </summary>
        public static string UserType_Influencer {
            get {
                return ResourceManager.GetString("UserType_Influencer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string UserType_Root {
            get {
                return ResourceManager.GetString("UserType_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to confirm your account email address. Please resend the confirmation email and try again..
        /// </summary>
        public static string Verify_Email_Message_Already_Confirmed {
            get {
                return ResourceManager.GetString("Verify_Email_Message_Already_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was not sent..
        /// </summary>
        public static string Verify_Email_Message_Fail {
            get {
                return ResourceManager.GetString("Verify_Email_Message_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your email exists on our system then you will soon receive an e-mail with instructions on confirming your account..
        /// </summary>
        public static string Verify_Email_Message_Resend_Confirmation {
            get {
                return ResourceManager.GetString("Verify_Email_Message_Resend_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email for account verification..
        /// </summary>
        public static string Verify_Email_Message_Success {
            get {
                return ResourceManager.GetString("Verify_Email_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify email token not found..
        /// </summary>
        public static string Verify_Email_Token_Not_Found {
            get {
                return ResourceManager.GetString("Verify_Email_Token_Not_Found", resourceCulture);
            }
        }
    }
}
